apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: ms-canary-demo
spec:
  replicas: 3
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: ms-canary-demo
  template:
    metadata:
      labels:
        app: ms-canary-demo
    spec:
      containers:
        - name: ms-canary-demo
          image: quay.io/codefresh/rollouts-demo:green
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: 32Mi
              cpu: 5m
  strategy:
    canary:
      steps:
        - setWeight: 33
        - pause: {duration: 15}
        - setWeight: 66
        - pause: {duration: 15}
