apiVersion: v1
kind: Service
metadata:
  name: canary-demo
  labels:
    test: ss
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: canary-demo
  type: ClusterIP
