kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: canary-demo
spec:
  args:
  - name: namespace
  metrics:
  - name: simple-http
    count: 6
    interval: 15s
    # failureCondition: result != '2'
    failureLimit: 5
    provider:
      web:
        url: "http://canary-demo.{{args.namespace}}:80"
        timeoutSeconds: 20 # defaults to 10 seconds